### PR TITLE
Fixes #6 using SSO Cookies

### LINKED ISSUE #6: Support for SSO accounts
It would be great if this supported SSO accounts.
https://www.safaribooksonline.com/enterprise/

### PR DESCRIPTION
**Pull request by wnds**
This PR fixes #6 by adding support for providing SSO cookies

### CODE REVIEW

**Comment by wnds** [comment]
This PR fixes #24

**Comment by ViciousPotato** [comment]
Thank you @wnds this is definitely a great improvement!

**Comment by acalderonsolano** [comment]
Thank you guys! I was waiting for the book_id with leading zero fix and it worked great :)

**Comment by wnds** [comment]
Sorry @ViciousPotato I missed testing form login and blindly removed code for form based login.

**Pull request merged**
